chore: fix vulnfix

diff --git a/.github/workflows/govulnfix.yml b/.github/workflows/govulnfix.yml
--- a/.github/workflows/govulnfix.yml
+++ b/.github/workflows/govulnfix.yml
@@ -32,12 +32,22 @@ jobs:
       - name: Install vulnfix
         run: go install github.com/hamba/vulnfix@latest
 
-      - name: Run govulncheck and update go.mod
-        # govulncheck exits 3 when vulnerabilities are found; pipeline should
-        # still reach vulnfix, so we use a subshell with pipefail disabled.
+      # govulncheck exits 3 when vulnerabilities are found; we want to continue to vulnfix, so we ignore the exit code.
+      - name: Run govulncheck
         run: |
-          set +o pipefail
-          govulncheck -json ./... | tee /tmp/vuln.json | vulnfix -o /tmp/vuln.md
+          go run golang.org/x/vuln/cmd/govulncheck@latest -format json ./... > /tmp/govulncheck-output.json; ec=$?
+          [[ $ec -eq 0 || $ec -eq 3 ]] || exit $ec
+
+      # Switch to the latest version of Go to ensure vulnfix can update the version of Go.
+      - name: Install Latest Go
+        uses: actions/setup-go@v6
+        with:
+          go-version: '1'
+          check-latest: true
+          cache: false
+
+      - name: Run vulnfix
+        run: vulnfix -o /tmp/vuln.md < /tmp/govulncheck-output.json
 
       - name: Open Pull Request
         uses: peter-evans/create-pull-request@v8
